apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: timer-to-log-embedded-1
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: timer-source
    properties:
      message: 'I am a very slow hardcoded message'
      period: '6000'
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
    properties:
      showAllProperties: 'true'