apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: timer-to-log-custom
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: timer-source
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink